name: PlayTimeLimit
version: '1.2'
main: org.radi8.playTimeLimit.PlayTimeLimit
api-version: '1.21'
authors: [ Andrew (radi8) ]
description: Per-day time limiting on Minecraft servers
website: https://modrinth.com/plugins/dailytimelimit

commands:
  get-time:
    description: retrieve the amount of time you've played this session/day
    usage: /<command> [today|all]

  leaderboard:
    description: get leaderboard of the time players have spent that day
    usage: /<command>